
repos:
  # basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json


  # format Prisma schema
  - repo: local
    hooks:
      - id: prisma-format
        name: prisma-format
        entry: npx
        args: [ "prisma", "format" ]
        language: node
        files: \\.prisma$
